<div class="lastcluops-block">
	<div class="lastcluops-header">
		<h3><?=lang('LAST_MODULE_CLUOPINIONS_AREA_TITLE')?></h3>
		<div class="lastcluops-right-corner"></div>
	</div>
	<div class="lastcluops-content">		<?$noline=True; foreach($opns_list as $row) { ?>		<div class="lastcluops-item" <?if($noline) $noline=False; else {?>style="border-top:1px solid #EBEBEB;"<?}?>>			<div class="item-logo">				<?=img(array('src'=>$row->logo, 'border'=>'0', 'align'=>'left'))?>			</div>			<div class="item-rate">				<?=lang('CLIENTS_REVIEWS_RATES');?><br>				<?if($row->rate <= 0) { ?>					<?=img(array('src'=>'images/ratings/helpfulls/bar_0.gif', 'id'=>"i{$row->rid}"))?>				<? } else if($row->rate >= 50) { ?>					<?=img(array('src'=>'images/ratings/helpfulls/bar_50.gif', 'id'=>"i{$row->rid}"))?>				<? } else { ?>					<?=img(array('src'=>'images/ratings/helpfulls/bar_'.$row->rate.'.gif', 'id'=>"i{$row->rid}"))?>				<? } ?>				<br>				<span><?=$row->opinionDATE?></span>				<br>			</div>			<div class="item-body">				<?=img(array('src'=>'images/ratings/stars'.ROUND($row->mark, 0).'.gif', 'border'=>'0'))?> <span class="r-title"><?=$row->title?></span>				<br>				<span class="sub"><?=sprintf(lang('CLIENTS_REVIEW_ON'), anchor("client/{$row->rid}-{$row->slug}", $row->name, 'alt="'.$row->name.'"'), $row->login)?></span><br>				<span class="sub"><strong><?=lang('CLIENTS_REVIEW_POS')?>:</strong> <?=$row->adv?></span><br>				<span class="sub"><strong><?=lang('CLIENTS_REVIEW_NEG')?>:</strong> <?=$row->disadv?></span><br> 				<p class="text">					<?=character_limiter(stripslashes($row->opinion), 512, '')?> <?=anchor("client/{$row->rid}-{$row->slug}#review", '...>>', 'alt="'.$row->name.'"')?>				</p>			</div>		</div>		<? } ?>		<span class="link-more">			<!-- 			<?=anchor('news', lang('LAST_MODULE_NEWS_ALL'), 'title="'.lang('LAST_MODULE_NEWS_ALL').'"')?>			 -->		</span>		<div style="clear:both"></div>	</div>		<div class="lastcluops-bottom-border">		<div class="lastcluops-footer-bar">
			<div class="lastcluops-bottom-right-corner"></div>
		</div>
	</div>	
</div>							