<?php/* * The Clients*/class Clients extends Controller{	private $objectsArr = array();
	public function __construct(){		parent::Controller();		$this->output->enable_profiler(False);		/* load needed libraries */					$this->load->library('settings_module');		$this->load->library('search_module');		$this->load->library('clients_module');		$this->load->library('mostpopular_module');		$this->load->library('advertise_module');		$this->load->library('navline_module');		$this->load->library('quickmenu_module');		$this->load->library('contacts_module');		$this->load->library('keywords_module');		/* generate objects */		$this->objectsArr['search_bar_obj'] = $this->search_module->RenderSearchBar();		$this->objectsArr['mostpopular_searches_obj'] = $this->mostpopular_module->RenderMostpopularSearchesArea();		$this->objectsArr['footermenu_area_obj'] = $this->quickmenu_module->RenderFootermenuArea();		$this->objectsArr['contactstoolbar_area_obj'] = $this->contacts_module->RenderContactsToolbar();		$this->objectsArr['metatitle_area_obj'] = $this->keywords_module->RenderMetatitleArea();		$this->objectsArr['metadescription_area_obj'] = $this->keywords_module->RenderMetadescriptionArea();	}
		public function index(){		$this->objectsArr['settings_area_obj'] = $this->settings_module->RenderSettingsArea();		$this->objectsArr['clients_list_obj'] = $this->clients_module->RenderRetailersList();		$this->objectsArr['keywords_area_obj'] = $this->keywords_module->RenderKeywordsArea($this->objectsArr['clients_list_obj']);				$this->load->view('layouts/clients/clients', $this->objectsArr);	}
	public function letter(){		$this->index();	}
	public function rules(){		$this->objectsArr['clients_rules_obj'] = $this->load->view('modules/clients_module/regrules.php', null, True);		$this->objectsArr['keywords_area_obj'] = $this->keywords_module->RenderKeywordsArea($this->objectsArr['clients_rules_obj']);		$this->load->view('layouts/clients/clientsrules', $this->objectsArr);	}
	public function regform(){		$this->objectsArr['clients_form_obj'] = $this->regProcessing();		$this->load->view('layouts/clients/clientsreg', $this->objectsArr);	}
	public function showproducts(){		$this->objectsArr['client_products_obj'] = $this->getClientProducts();		$this->objectsArr['keywords_area_obj'] = $this->keywords_module->RenderKeywordsArea($this->objectsArr['client_products_obj']);		$this->load->view('layouts/clients/clientproducts', $this->objectsArr);	}
	public function client($clientSlug, $page = 0){		$this->objectsArr['client_info_obj'] = $this->clients_module->renderClientInfo($clientSlug, $page);		$this->objectsArr['keywords_area_obj'] = $this->keywords_module->RenderKeywordsArea($this->objectsArr['client_info_obj']);		$this->load->view('layouts/clients/clientinfo', $this->objectsArr);	}
	public function redirect($cRid=null){		if(!$cRid) redirect('clients', 'refresh');		$this->clients_module->redirectToClient($cRid);	}		public function reviewrate(){		$this->output->enable_profiler(False);		$this->output->set_output($this->clients_module->rateReview());		}	
	public function regProcessing(){		return $this->clients_module->registerProcessing();	}
	public function getClientProducts(){		return $this->clients_module->getClientProducts();	}
	public function editreview($clientSlug){		$this->objectsArr['client_info_obj'] = $this->clients_module->reviewProcessing($clientSlug);		$this->objectsArr['keywords_area_obj'] = $this->keywords_module->RenderKeywordsArea($this->objectsArr['client_info_obj']);		$this->load->view('layouts/clients/editreview', $this->objectsArr);	}	
}
?>